### ISSUE TITLE
Plugin disabling chat on java 21.

### ISSUE THREAD

**Issue by matipoirierg** [LOOHP/InteractiveChat#201] opened 2024-04-24 13:55 UTC
[13:52:35 WARN]: [InteractiveChat] Plugin InteractiveChat v4.2.9.0 generated an exception while executing task 228174
java.lang.IllegalArgumentException: Unexpected type: class io.papermc.paper.adventure.AdventureComponent
        at InteractiveChat-4.2.9.0.jar/com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:197) ~[InteractiveChat-4.2.9.0.jar:?]
        at InteractiveChat-4.2.9.0.jar/com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.9.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.20.4.jar:git-Leaf-"3669cb6"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.20.4.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        
        Chat stopped working after this error.

**Comment by LOOHP** [comment] 2024-04-24 13:57
Duplicate of #198.

**Closed by LOOHP** 2024-04-24 13:57 UTC
