### ISSUE TITLE
Hover feature broken on 4.2.9.1 version

### ISSUE THREAD

**Issue by DarkChromaMC** [LOOHP/InteractiveChat#205] opened 2024-05-03 05:31 UTC
I'm running on 1.20.4 using version 4.2.9.1 for InteractiveChat. Everything is fine except when I hover over a [item] in chat, it doesn't show the items unique properties, like enchantments, lore, name, etc.

However, version 4.2.9.0 was working fine. But, this version only supports up to 1.20.2 so is there a way the latest version can support hovering over items?

Version 4.2.9.1 (latest)
https://github.com/LOOHP/InteractiveChat/assets/68839442/46d1de6d-d3ee-4d24-b438-27ea423ac319

Version 4.2.9.0 (old)
https://github.com/LOOHP/InteractiveChat/assets/68839442/03cd292f-19fb-4e4c-91ab-97cf1e809426

**Comment by XLordalX** [comment] 2024-05-06 06:59
Having the same issue.

**Comment by ediTv2** [comment] 2024-05-06 07:02
Issue is present for me aswell.

**Comment by LOOHP** [comment] 2024-05-07 15:53
Confirmed, it wasa due to a change in the latest version of Adventure library. Will be fixed in the next update soon.

**Closed** 2024-05-11 14:01 UTC
